apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx-k8s-pods-sa
      containers:
        - name: nginx
          image: us-west1-docker.pkg.dev/som-rit-infrastructure-prod/third-party/nginx:build-20 # {"$imagepolicy": "flux-system-new:podinfo"}
          ports:
            - containerPort: 80

